config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i[create new show]
  resources :events, only: %i[create new index show]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :event_attendees
  has_many :attendees, through: :event_attendees
  validates :title, :description, :location, :date, presence: true

  scope :upcoming_events, -> { where('date > ?', Date.today) }
  scope :previous_events, -> { where('date < ?', Date.today) }
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :event
  belongs_to :attendee, class_name: 'User', foreign_key: :attendee_id
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, class_name: 'Event', foreign_key: :creator_id
  has_many :event_attendees, foreign_key: 'attendee_id'
  has_many :attended_events, through: :event_attendees, source: :event
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :not_blank?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    return if logged_in?

    flash[:alert] = 'you must be logged in to perfom that action'
    redirect_to login_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in?, only: [:create]

  def index
    @events = Event.all
    @upcoming_events = @events.upcoming_events
    @previous_events = @events.previous_events
  end

  def show
    @event = Event.find(params[:id])
    @attendees = User.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      flash.notice = 'Event created'
      redirect_to @event
    else
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:date, :description, :location, :title)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if params[:session][:username].blank?
      render 'new'
      flash.alert = 'Please enter your name'
    else
      user = User.find_by_username(params[:session][:username])
      if user.present?
        session[:user_id] = user.id
        redirect_to root_url, notice: 'Logged in!'
      else
        flash.now[:alert] = 'sign up before you login'
        render 'new'
      end
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @created_events = @user.created_events
    @attended_events = @user.attended_events
    @upcoming_events = current_user.attended_events.upcoming_events
    @previous_events = current_user.attended_events.previous_events
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash.notice = "Account created succesfully welcome #{@user.username}.Please sign in."
      redirect_to login_path
    else
      flash.now[:notice] = 'Please enter your name'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<div class = "container mt-3">
  <% if logged_in? %>
    <%= link_to 'Create new event', new_event_path, class: 'btn btn-success mb-2' %>
  <% end -%>
  <div class = 'row'>
      <div class = 'col-6 card p-3 text-center'>
          <h3>All events</h3>
              <% @events.each do |event| %>
                  <p><strong>Date:</strong> <%= event.date %></p>
                  <p><strong>Title:</strong> <%= event.title %></p>
                  <p><strong>Description:</strong> <%= event.description %></p>
                  <p><strong>Location:</strong> <%= event.location %></p>
                  <p><strong>Host:</strong> <%= event.creator.username.capitalize %></p>
                  <p><%= link_to 'Check attendee here', event_path(event), class: 'btn btn-warning' %> </p>
                  <hr>
              <% end %>
      </div>

      <div class = 'col-6 card p-3 text-center'>
        <h3>Upcoming events</h3>
        <% @upcoming_events.each do |event| %>
        <p><strong>Host:</strong> <%= event.creator.username.capitalize %></p>
        <p><strong>Date:</strong> <%= event.date %></p>
        <p><strong>Title:</strong> <%= event.title %></p>
        <p class= "border-bottom border-success pb-3"><strong>Location:</strong> <%= event.location %></p>
        <% end %>
        <h3>Past Events</h3>
        <% @previous_events.each do |event| %>
        <p><strong>Host:</strong> <%= event.creator.username.capitalize %></p>
        <p><strong>Date:</strong> <%= event.date %></p>
        <p><strong>Title:</strong> <%= event.title %></p>
        <p class= "border-bottom border-success pb-3"><strong>Location:</strong> <%= event.location %></p>
        <% end %>
      </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="row container h-4">
  <div class="col-6 ">
    <div class="container mt-3 card-bg shdw p-3">
  <h1 class="mt-3">Create an Event</h1>
<%= form_with(model: @event, class: "shadow p-3 mb-3 form-bg rounded", local: true) do |f| %>
<%= render 'shared/error_messages' %>
<div class="form-group ">
  <%=f.label :title%>
  <%=f.text_field :title, class: "form-control"%>
</div>
<div class="form-group ">
  <%=f.label :location%>
  <%=f.text_field :location, class: "form-control"%>
</div>
<div class="form-group ">
  <%=f.label :date%>
   <%= f.date_field :date, class: "form-control" %>
</div>
<div class="form-group ">
  <%=f.label :description%>
  <%=f.text_area :description, class: "form-control"%>
</div>
  <div class="form-group">
    <%=f.submit "Create Event", class: "btn btn-success"%>
  </div>
  
<% end %>
</div>
    
  </div>
</div>

app/views/events/show.html.erb
<div class="container text-center card">
   <h1>Title:<%= @event.title %></h1>
        <h3>Host: <%= @event.creator.username.capitalize %></h3>
        <h1>Attendee:</h1>
        <% @attendees.each do |attendee| %>
        <p><%= attendee.username%></p>
        <% end %>
    <hr>
  
    <p><%= link_to 'New event', new_event_path, class: 'btn btn-success' %></p>

    <p><%= link_to 'Home', root_path, class: 'btn btn-warning' %></p>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="main-footer p-3 text-white mt-5">
    <div class="container text-center">
        <small>Copyright &copy; <%=link_to "Private Event", "#", class: "text-white" %></small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success text-center w-50 container mt-2'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger text-center w-50 container mt-2'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light  text-font">
  <%=link_to "Private Event", root_path, class: "navbar-brand text-white" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse container " id="navbarNav">
    <% if logged_in?%>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active mr-4">
        <%= link_to "Create Event", new_event_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item active mr-4">
        <%= link_to "My Events", user_path(current_user), class: "nav-link text-white" %>
      </li>
      <li class="nav-item mr-4">
      <%=link_to('Logout', logout_path, class: "btn btn-xs btn-danger shadow mr-3", method: :delete)%>
      </li>
    </ul>
    <% else %>

     <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
          <%= link_to "Sign In", login_path, class: "nav-link text-white " %>
        </li>
       <li class="nav-item active">
        <%= link_to "Sign Up", new_user_path, class: "nav-link text-white " %>
      </li>
    </ul>
    
  <% end -%>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navbar' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  <%=render 'layouts/footer' %>  
</body>
</html>

app/views/shared/_error_messages.erb
 <% if @event.errors.any? %>
<div id="error_explanation">
<div class="alert alert-danger">
The form contains <%= pluralize(@event.errors.count, "error") %>.
</div>
<ul>
<% @event.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/users/index.html.erb
<h1>welcome to the Event</h1>

app/views/users/new.html.erb
<div class="container mt-3 w-50 card-bg shdw p-3">
	<h1 class="mt-3">Sign up</h1>
<%= form_with model: @user, class: "form-group" do |f| %>
<div class="form-group ">
	<%=f.label :username%>
  <%=f.text_field :username, class: "form-control"%>
</div>
  <div class="form-group">
  	<%=f.submit "sign up", class: "btn btn-success"%>
  </div>
  
<% end %>
</div>

app/views/users/show.html.erb
<div class="container card mt-3">
    <div class='row'>
        <div class='col-6'>
            <h1>Events you created:</h1>
            <% @created_events.each do |event| %>
            <p><strong>Host:</strong>
                <%= event.creator.username.capitalize %>
            </p>
            <p><strong>Date:</strong>
                <%= event.date %>
            </p>
            <p><strong>Title:</strong>
                <%= event.title %>
            </p>
            <p><strong>Description:</strong>
                <%= event.description %>
            </p>
            <p class="border-bottom border-success"><strong>Location:</strong>
                <%= event.location %>
            </p>
            <% end %>
        </div>

		  <div class='col-6'>
            <h1>Events you attended:</h1>
            <% @attended_events.each do |event| %>
            <p><strong>Host:</strong>
                <%= event.creator.username.capitalize %>
            </p>
            <p><strong>Date:</strong>
                <%= event.date %>
            </p>
            <p><strong>Title:</strong>
                <%= event.title %>
            </p>
            <p><strong>Description:</strong>
                <%= event.description %>
            </p>
            <p class="border-bottom border-success"><strong>Location:</strong>
                <%= event.location %>
            </p>
            <% end %>
        </div>


        <div class='col-6 border-left border-success'>
            <h3>Upcoming events</h1>
                <% @upcoming_events.each do |event| %>
                <h1>Events created by host:
                    <%= event.creator.username %>
                </h1>
                <p><strong>Date:</strong>
                    <%= event.date %>
                </p>
                <p><strong>Title:</strong>
                    <%= event.title %>
                </p>
                <p><strong>Location:</strong>
                    <%= event.location %>
                </p>
                <% end %>
                <hr>
                <h3>Past Events</h1>
                    <% @previous_events.each do |event| %>
                    <h3>Events created by host:
                        <%= event.creator.username %>
                        </h1>
                        <p><strong>Date:</strong>
                            <%= event.date %>
                        </p>
                        <p><strong>Title:</strong>
                            <%= event.title %>
                        </p>
                        <p><strong>Location:</strong>
                            <%= event.location %>
                        </p>
                        <% end %>
        </div>
        <p>
            <%= link_to 'Back to Home', root_path, class: 'btn btn-warning ml-2' %>
        </p>
    </div>